### ISSUE TITLE
Week 8+9

### ISSUE THREAD

**Issue by MarieShaikov** [MarieShaikov/Python-012021#6]
Ahoj Andy @andywaltlova, moc dekuji za opravu ukolu z Week 4 a 5. 

Dnes jsme dodelala Django pro week 8 a 9 (ukoly 36-45), jen jsem nevedela jaky zkusebni zaznam na konci udelat. (posledni veta ze zadani: _Opět proveď migraci databáze, zaregistruj model do administrátorského rozhraní a vytvoř nějaký zkušební záznam_.) Migraci jsem udelala, model jsem registrovala, jen ten zkusebni zaznam jsem nevedela co presne znamena. 

Tady je odkaz na projekt **Pujcovna**: https://github.com/MarieShaikov/Python-012021/tree/master/pujcovna
Kdyby jsi se potrebovala prihlasit k web.strance prihlasovaci udaje jsou: Username:marieshaikovski, Password: admin123

Chybi mi ted jenom asi uz dodelat Week 6 a Week 7, mam tyhle ukoly poslat ke kontrole nekomu jinemu z koucu? Napis mi, pokud toho mas ted hodne a komu bych pripadne mohla ukoly poslat ke kontrole. 

Dekuji a drzim palce do zkouskoveho obdobi!

**Comment by andywaltlova** [comment]
Ahoj, díky. Nemusíš posílat nikomu jinému, zvládnu to opravit během zítřka (do začátku poslední lekce) :)

**Comment by andywaltlova** [comment]
Heslo k databazi nepotrebuji, vzhledem k tomu ze si ji posilame jako soubor - coz by normalne samozrejme nebylo bezpecne, mohu na ni take zavolat createsuperuser a vytvorit si vlastniho superuzivatele.
Zkusebnim zaznamem se mysli jen to ze se prihlasis do toho admin prostredi a zkusis si do modelu pridat novy zaznam tim ze vyplnis ty policka - coz koukam ze jsi udelala :)

## Week 8 |  5b✔️ 
Super, vytvoreni a nastaveni projektu je v poradku 👍 

## Week 9 | 5b✔️ 
Taky pekne, vsechny modely mas dobre vytvorene, v db vidim i ty zkusebni zaznamy 👍 

---
Momentalne mas 35b, ukoly chybi z tydnu 6,7 a 10,11 - bodu mas na certifikat dost, takze mi ty zbyvajici proste posli az je budes mit hotove :)
